freebsd_instance:
  image: freebsd-13-1-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[!0f42e3f70fd51cdeddfe7e98160982fc9efe7e8a26869b725fcd5de05d067a7100b994cf52f0f1b470a983148e0b8ec2!]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-13-1-release-amd64
  auto_cancellation: false
  stateful: false
  setup_script:
    - pkg install -y curl wget zip pkgconf cmake qt5-x11extras qt5-quickcontrols qt5-qmake qt5-widgets qt5-buildtools qt5-concurrent kf5-kdbusaddons kf5-kwindowsystem kf5-baloo libdbusmenu-qt5 pulseaudio pulseaudio-qt libXcomposite
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - make DESTDIR=Menu.app -j$(sysctl -n hw.ncpu) install
    - mkdir -p Menu.app/Resources
    - cp ../Menubar.png Menu.app/Resources/Menu.png
    - ( cd Menu.app/ ; ln -s usr/bin/Menu Menu )
    - rm -rf Menu.app/usr/include
    - mkdir -p ../Shutdown/build
    - cd ../Shutdown/build
    - cmake ..
    - make -j$(sysctl -n hw.ncpu)
    - cd -
    - cp ../Shutdown/build/Shutdown Menu.app/usr/bin/
    - find Menu.app/
    - zip --symlinks -r Menu_FreeBSD.zip Menu.app/
    # curl --upload-file ./Filer_FreeBSD.zip https://transfer.sh/Filer_FreeBSD.zip
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
