freebsd_instance:
  image: freebsd-13-1-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[88b74679b162640cd98fb4b6915e478559ba058e76bd15f08181be79bb3d9fb957f6df442acca2c657aed61a074eb628]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-13-1-release-amd64
  auto_cancellation: false
  stateful: false
  setup_script:
    - pkg install -y curl wget zip pkgconf cmake qt5-x11extras qt5-quickcontrols qt5-qmake qt5-widgets qt5-buildtools qt5-concurrent kf5-kdbusaddons kf5-kwindowsystem kf5-baloo kf5-kglobalaccel libdbusmenu-qt5 pulseaudio pulseaudio-qt libXcomposite libqalculate
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make DESTDIR=. -j$(sysctl -n hw.ncpu) install
    - find System/Menu.app/
    - ( cd ./System/ ; zip --symlinks -r ../Menu_FreeBSD.zip Menu.app/ )
    # curl --upload-file ./Filer_FreeBSD.zip https://transfer.sh/Filer_FreeBSD.zip
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
